"""initial schema

Revision ID: c712fe897b6f
Revises: 
Create Date: 2026-07-20 20:24:37.192770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'c712fe897b6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # Enable pgvector extension — required before any vector() column can be used.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic ###
    op.create_table(
        'source_documents',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('file_name', sa.String(), nullable=False),
        sa.Column('source_url', sa.String(), nullable=True),
        sa.Column('filing_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'chat_threads',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'document_chunks',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('document_id', sa.UUID(), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=False),
        sa.Column('page', sa.String(), nullable=True),
        sa.Column('section', sa.String(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('embedding', pgvector.sqlalchemy.Vector(1536), nullable=True),
        sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
        sa.Column('token_count', sa.Integer(), nullable=False),
        sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'chat_messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('thread_id', sa.UUID(), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('ai_sdk_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'message_citations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('message_id', sa.UUID(), nullable=False),
        sa.Column('chunk_id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ),
        sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # HNSW index for pgvector semantic search over chunk embeddings.
    # cosine distance matches OpenAI embedding space.
    op.execute("""
        CREATE INDEX document_chunks_embedding_hnsw_idx
        ON document_chunks
        USING hnsw (embedding vector_cosine_ops)
    """)

    # GIN index for Postgres full-text search over the tsvector column.
    op.execute("""
        CREATE INDEX document_chunks_search_vector_gin_idx
        ON document_chunks
        USING gin (search_vector)
    """)

    # GIN index on chunk_metadata JSONB for fast filing metadata filtering.
    op.execute("""
        CREATE INDEX document_chunks_chunk_metadata_gin_idx
        ON document_chunks
        USING gin (chunk_metadata)
    """)

    # Row Level Security: users can only read their own chat threads and messages.
    op.execute("ALTER TABLE chat_threads ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY")

    op.execute("""
        CREATE POLICY chat_threads_owner_policy ON chat_threads
        USING (user_id = (current_setting('request.jwt.claims', true)::jsonb->>'sub')::uuid)
    """)
    op.execute("""
        CREATE POLICY chat_messages_owner_policy ON chat_messages
        USING (
            thread_id IN (
                SELECT id FROM chat_threads
                WHERE user_id = (current_setting('request.jwt.claims', true)::jsonb->>'sub')::uuid
            )
        )
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop RLS policies before tables
    op.execute("DROP POLICY IF EXISTS chat_messages_owner_policy ON chat_messages")
    op.execute("DROP POLICY IF EXISTS chat_threads_owner_policy ON chat_threads")

    op.drop_table('message_citations')
    op.drop_table('chat_messages')
    op.drop_table('document_chunks')
    op.drop_table('chat_threads')
    op.drop_table('users')
    op.drop_table('source_documents')
